# Generated by Django 2.0.5 on 2018-05-12 20:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='photo',
            field = models.ImageField(upload_to='images', verbose_name='фото юзера'),
        ),
    ]
