# Generated by Django 2.0.5 on 2018-05-13 00:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_auto_20180512_2330'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='photo',
            field=models.ImageField(upload_to='images', verbose_name='photo'),
        ),
    ]
