WIN_BLOCK_SIZE = WIN_BLOCK_WIDTH, WIN_BLOCK_HEIGHT = 28, 34
BLOCK_SIZE = BLOCK_WIDTH, BLOCK_HEIGHT = 20, 20
WIN_SIZE = WIN_WIDTH, WIN_HEIGHT = WIN_BLOCK_WIDTH * BLOCK_WIDTH, WIN_BLOCK_HEIGHT * BLOCK_HEIGHT
BG_COLOR = 0, 0, 0
SEED_SIZE = SEED_WIDTH, SEED_HEIGHT = 6, 6
BIG_SEED_SIZE = BIG_SEED_WIDTH, BIG_SEED_HEIGHT = 12, 12