# Generated by Django 2.0.5 on 2018-05-07 00:56

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Session',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(verbose_name='Код')),
                ('name', models.CharField(default='session', max_length=24, verbose_name='Название сессии')),
                ('token', models.CharField(max_length=15, verbose_name='Уникальный токен')),
                ('datetime', models.DateTimeField(auto_now_add=True, verbose_name='Дата и время создания')),
                ('lifetime', models.IntegerField(verbose_name='Время жизни в часах')),
                ('language', models.CharField(max_length=20, verbose_name='Язык программирования сессии')),
                ('users', models.ManyToManyField(to=settings.AUTH_USER_MODEL, verbose_name='Подключенные люди')),
            ],
        ),
    ]
